### ISSUE TITLE
[proposal] - Kanye Draw – Draw Kanye, with Kanye

### ISSUE THREAD

**Issue by JohJakob** [tholman/inspiring-online#104]
http://kanyedraw.com

**Comment by vaidaslamanauskas** [comment]
We already had Trump draw. Isn't it too similar? :)

**Comment by tholman** [comment]
Could edit the trump draw and group them together. All related to
presidents a bit too.

On Sun, Feb 14, 2016 at 12:57 PM, Vaidas L. <notifications@github.com>
wrote:

> We already had Trump draw. Isn't it too similar? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tholman/inspiring-online/issues/104#issuecomment-183938750>
> .
>



-- 
Tim Holman
tholman.com
