### ISSUE TITLE
Possible issue with the gem Kramdown (maybe add it to readme)?

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#109]
I've used Jekyll before and everything worked fine. However, when I tried it with this site it said that Kramdown was missing or one of its dependencies was, even though I could see that it was installed.

[This page](http://stackoverflow.com/questions/31417469/jekyll-ruby-kramdown-missing-dependency) helped in telling me to do `bundle exec jekyll serve` instead of just `jekyll serve` as suggested on the jekyll website and this site's README. While that helped, I think it might be good to add that solution to the README as a suggestion if things aren't working because it took me a good half an hour to come upon this solution.

_(It's also possible that I only ran into this problem because I don't understand how Jekyll and Bundle work enough, so feel free to ignore this.)_

**Comment by JohJakob** [comment]
I didn't run into this problem, instead Jekyll showed me this message:
> Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.

I've installed Jekyll 3, so you have to include `jekyll-paginate` in Gemfile and _config.yml ([Documentation](http://jekyllrb.com/docs/pagination)).
@tholman Does Inspiring Online run on Jekyll 2?

**Comment by TJScalzo** [comment]
@JohJakob I saw that error message too. However, when I ran Jekyll using `bundle exec jekyll serve` it didn't give that error message anymore. I'm not positive why that is though.

**Comment by tholman** [comment]
It could be that its an old version (was created before 3 was out?) ... I can check if I grab some time. Is there a quick way to tell?

**Comment by JohJakob** [comment]
@TJScalzo Yeah, it works with `bundle exec jekyll serve`. This is weird, but we should add a hint to the README for now.

**Comment by tholman** [comment]
Ahh right, I am on jekyll `2.5.1` ... which explains why I'm getting a different shebangle to everyone else... Going to look into it a little now, and update.

**Comment by tholman** [comment]
Looks like we have a `bundle exec jekyll serve` in the readme now... (recently added?)

I've added the pagination gem as a requirement in the config file.

I also quickly updated my jekyll version with

`gem update jekyll`
`bundle install`

Seems like I'm not getting any more warnings after that, either. So feels good here, to close this one... But please open if you've still got problems! :dancer:
