### ISSUE TITLE
No favicon!

### ISSUE THREAD

**Issue by tholman** [tholman/inspiring-online#11]
Gotta get one of those. I guess we don't really have a brand. But we can figure that out!

**Comment by syntiux** [comment]
![favicon](https://cloud.githubusercontent.com/assets/2430239/10742189/250265de-7c2c-11e5-9c7c-108a45fa2d07.png)
![favicon](https://cloud.githubusercontent.com/assets/2430239/10742195/2e04811c-7c2c-11e5-9d59-122c36218388.png)

I quickly made one. It's supposed to look like an ascii smiley while also having i.o (inspiring.online) in it. What do you think?

**Comment by tholman** [comment]
Love it! Get that in a PR! :dancer:

**Comment by tholman** [comment]
Seriously, great stuff :D
