### ISSUE TITLE
The Github Corner is very tiny on mobile and smallish on desktop

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#114]
### On Mobile:
- The triangle takes up less space than the "Ly" of the post that's at the top of the page.
- The octocat is indistinguishable from the grey around it due its size.
- The scroll bar that shows up on iPhone Safari covers nearly the entire thing

Vertical:
![Vertical iPhone screenshot](https://cloud.githubusercontent.com/assets/15825214/13375709/f799c79a-dd74-11e5-83ed-cabc39da8597.png)
Horizontal:
![Horizontal iPhone screenshot](https://cloud.githubusercontent.com/assets/15825214/13375710/f7a1b23e-dd74-11e5-863c-d6d997940323.png)

These are things that can easily be fixed using media queries. However, I'll only fix it on mobile for now since I was explicitly told the size to make the triangle on desktop and I don't want to go against that.

### On Desktop:
- When I showed it to some people, they didn't notice anything different.
- The combination of its size and the fact that it's all the way to the right (an area that has nothing that would make people look there) makes it very unlikely that people would notice it.
![Screenshot of desktop](https://cloud.githubusercontent.com/assets/15825214/13375655/adccda22-dd73-11e5-91cf-4fd5e16b104f.png)

(**By the way:** I don't mean to be passive-aggressive or anything like that, I'm just pointing out that the triangle seems very small to me.)

**Comment by TJScalzo** [comment]
In attempting to do this I've determined that, if there _is_ a mobile version of this site, it's indistinguishable from the desktop one. 
To me, the mobile site looks like the regular site scaled down to fit onto the screen and then extended at the bottom so that it fills the screen. 

Therefore, I made a new issue: [Make site better on mobile devices](https://github.com/tholman/inspiring-online/issues/115)

**Comment by TJScalzo** [comment]
After a couple more hours of fiddling with this, I'm basically saying is that unless a mobile version is created, it'll very difficult to make this look good on mobile. (I say this mainly because media queries stopped working for some reason and I can't figure out why.)

Also, the desktop version could do with having the corner be a little larger.

**Comment by tholman** [comment]
You're definitely right about the size of the icon (my bad, really!) 

3/4 of full size looks great to me... we should perhaps change that. 

I'm looking into the mobile thing now. Added the viewport meta, so its a bit better, at least.

**Comment by TJScalzo** [comment]
I'll create a pull request that makes the corner at that size

**Comment by JohJakob** [comment]
@TJScalzo Awesome! Thanks!
