### ISSUE TITLE
Make site better on mobile devices

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#115]
Right now, everything is just scaled down to fit on a mobile screen. This has resulted in many things being very small and difficult to read.
#### Problems on mobile:
- [X] Add viewport meta tag
- [x] There is no menu at all; could become a header with dropdowns?
- [x] When in landscape mode the menu is only half shown.
- [x] The next and previous buttons are almost cut off and are only at the bottom of the page
- [x] There's no way to get back to home page (A home button could be added in middle between next and previous?)
- [x] The navs have weird padding.
- [ ] The menu takes up a lot of space.
- [x] ~~The menu doesn't stay at the top of the viewport. (Probably because it would cover half the page if it did)~~

**Comment by vaidaslamanauskas** [comment]
We haven't looked into this yet. I'm not sure how many visits are there from mobile devices. Improving step by step here. Will look into this.

**Comment by tholman** [comment]
Sorry for being slow, I'm on the road. Not seeing everything. Weird though, must have lost our viewport meta tag somewhere (or never had it)

**Comment by TJScalzo** [comment]
I remember seeing something about a viewport meta tag in documentation for media queries but I wasn't sure what it did. Things are looking much better now!
However, when in landscape mode the menu on the left is still visible, but only a small part of it. So there are obviously still some things that need work.

**Comment by TJScalzo** [comment]
### Here are some screenshots:
Landscape - menu sort of shows up but is cut off:
![image](https://cloud.githubusercontent.com/assets/15825214/13464340/c3efd776-e05e-11e5-8947-908b3c3ff039.png)
Portrait - next and previous buttons aren't positioned well:
![image](https://cloud.githubusercontent.com/assets/15825214/13464341/c40c0f7c-e05e-11e5-84d2-6a5eb64c2746.jpeg)

I'm not completely sure how the menu should be displayed on mobile so I'd really love some ideas/opinions.

**Comment by JohJakob** [comment]
Navigation drawers/Hamburger menus are boring. I would make a tab bar like navigation, only with icons.

**Comment by vaidaslamanauskas** [comment]
'Hamburger' menus aren't boring, they are completely unnecessary. Changing position to relative on mobile widths might be good enough ;)

**Comment by TJScalzo** [comment]
@JohJakob The issue with using icons is coming up with one that effectively demonstrates "Contributors" or "Join in?" I'm not very good at communicating things in that way.

@vaidaslamanauskas Do you mean make the menu that's normally on the side sit at the top of the page in its entirety? I think I'll try to do that.

I will post a screenshot of my test before committing because I know that I'll do something strangely that can be done better.

**Comment by vaidaslamanauskas** [comment]
@TJScalzo I guess :)

**Comment by JohJakob** [comment]
I thought about a menu at the top of the page, but you would have to hide it behind a button or something because it would fill too much space without. I'm curious about what you have in mind.

**Comment by vaidaslamanauskas** [comment]
You don't need to fit everything. Only what mobile user might need.
Actually, having little description on the top and then just the content might be enough for a mobile user. Darn, we are not gonna run A/B tests for this :) Have fun boys.

**Comment by TJScalzo** [comment]
Okay, it turns out that I have no idea how to make a navigation bar for mobile. Every time I try to make something it ends up not working for some reason. I don't _want_ to admit defeat, but I am. I've spent way more time on this with basically nothing to show for it. Would someone else like to take a stab at this? (@JohJakob / @vaidaslamanauskas)

**Comment by vaidaslamanauskas** [comment]
Don't worry, @TJScalzo. There's plenty of stuff todo on this project.

**Comment by TJScalzo** [comment]
Thank you @vaidaslamanauskas! I actually just fixed the issue with the buttons being right at the edge of the page on mobile.

**Comment by TJScalzo** [comment]
The nav menu could do with some improvements. Also, there's an oddly large amounts of space between the content and the navs (the menu and the author thing).

**Comment by TJScalzo** [comment]
I can't seem to reopen this issue... It probably has to do with my not having write access.

**Comment by meowwwls** [comment]
I took a stab at this. I thought it might be nice to reuse the logo from the 404 page as a trigger for the mobile nav. 

![mobile nav](http://res.cloudinary.com/meowwwls/image/upload/v1457777868/mobile-nav-io_s4mnee.gif)

**Comment by Haroenv** [comment]
Technically, that looks amazing, but from a practical standpoint I **personally** prefer visible menus.

**Comment by JohJakob** [comment]
@meowwwls This looks neat. I don't prefer visible menus, it's rather based on the website and the menu. But it needs some additions:
1. It must be clear that the logo hides a menu.
2. I would show the rays only when the menu is open.
3. I would use a different open/close animation.
4. A backdrop effect could look cool: `-webkit-backdrop-filter: blur(4px)` (only for Safari at the moment)

**Comment by meowwwls** [comment]
@JohJakob I implemented all of those suggestions. Is this better? I used your animation from the 404 page for the rays when the menu opens as well.

![mobile nav attempt 2](http://res.cloudinary.com/meowwwls/image/upload/v1457783244/mob-io-002_qbm3zf.gif)

Backdrop blur on Safari:

![backdrop blur](http://res.cloudinary.com/meowwwls/image/upload/c_scale,h_621/v1457783244/safari-bg-blur-io_t7s8ca.png)

**Comment by Haroenv** [comment]
Definitely more clear now :heart:

**Comment by JohJakob** [comment]
@meowwwls Will the rays stay visible when the animation is over?

**Comment by meowwwls** [comment]
@JohJakob Yes, they remain visible once the animation is over, as long as the navigation is open.

**Comment by JohJakob** [comment]
@meowwwls There could be more space between "Menu" and the line.

**Comment by meowwwls** [comment]
@JohJakob Sorry about that. I fixed it but must not have refreshed before taking the screenshot.

On Safari:
![fixed spacing between border on mobile nav](http://res.cloudinary.com/meowwwls/image/upload/c_scale,h_492/v1457784369/mob-nav-saf-space-io_dlnrlo.png)

**Comment by JohJakob** [comment]
@meowwwls Awesome! Now we have to wait for @tholman's, @TJScalzo's, @vaidaslamanauskas's and @Haroenv's opinions.

**Comment by Haroenv** [comment]
:shipit:

**Comment by vaidaslamanauskas** [comment]
Gonna be harsh. What is the point? I mean it is fun and all. But there is not enough menu items to reason hiding them. I would prefer one click to get where I want.

But this site is for fun and experiments. So f**k it :+1:

**Comment by TJScalzo** [comment]
@meowwwls that looks awesome! Does the menu stick to the top of the window, like the GitHub Corner or does it stay at the top page and can be scrolled past? I feel like it should always be visible now that it's much smaller.

@vaidaslamanauskas I feel like the reason for this is to make it easy to navigate the site on mobile. If the menu were kept in its current form then the user would have to scroll back up to the top of the page every time they want to go to the home page or look at the contributors. Sure, a menu that requires two taps takes a little bit more time, but it takes even more time to scroll up to the top of the page.

**Comment by vaidaslamanauskas** [comment]
@TJScalzo Fixed mobile menu would be terrible. No no.

**Comment by TJScalzo** [comment]
Aw, why @vaidaalamanauskas?

**Comment by Haroenv** [comment]
Well I'm also against fixed things that are large on mobile.

**Comment by JohJakob** [comment]
Would it be possible to condense the menu like the navigation bar in some apps, so it would be still clickable, but wouldn't take up so much space? For example, when scrolling, the logo fades out and the surrounding whitespace would shrink to the height of the GitHub Corner.

**Comment by vaidaslamanauskas** [comment]
@JohJakob Overdoing a bit? :)

**Comment by TJScalzo** [comment]
@meowwwls, can you post a gif of the menu you made with it opening, closing, and scrolling? I'm interested in seeing how much it covers the content of the page?

**Comment by vaidaslamanauskas** [comment]
@TJScalzo It would. Even a small bar is unnecessary. Too many screen sizes to tackle.
Plus, we only have 10 posts per page. It is not infinite scrolling bonanza :)

**Comment by meowwwls** [comment]
@TJScalzo No, it isn't fixed. I tried that at first, but I wasn't happy with how it looked when scrolling, with the logo bar covering a fair amount of every post. 

![open nav scrolling](http://res.cloudinary.com/meowwwls/image/upload/v1457822987/open-nav-scroll-io_kvimmn.gif)

@JohJakob I'm limited in my skillset, so that's not something I really know how to do, if I'm imagining it correctly.

@vaidaslamanauskas Pretty much "I like how it looks and the site is for fun, so f*ck it" was my thought process. ;)

**Comment by Haroenv** [comment]
@moewwwls :heart:

**Comment by TJScalzo** [comment]
I know when to pick my battles and it's clear that I won't win this one. So I say that what @meowwwls has made is nearly perfect. The changes I want made are hard to explain. So I say add the menu as it is now (which is very good) and I'll try and see if I can explain after looking at the code.

**Comment by vaidaslamanauskas** [comment]
Okay, in terms of 'UX bullshiterry', it is not a good idea for this kind of site. And there are of course better ways.
**BUT**
This is open source place for weird, exciting, inspiring web. So I wouldn't mind if the menu screamed on the press.

@meowwwls Welcome. Good contribution. Make a pull request and I'll or other dudes will merge it.
:heart:

**Comment by TJScalzo** [comment]
> Okay, in terms of 'UX bullshiterry', it is not a good idea for this kind of site. And there are of course better ways.

@vaidaslamanauskas, can you please provide a better way? Or perhaps explain specifically why this isn't good for this site? You're welcome to your opinion and I'd really like to understand it better. Do you mean that the current menu is better than what @meowwwls has made?

I ask because I want to see if there might be some way to compromise our two views:
**Me:** The menu on mobile is very bulky and should be slimmed down. The proposed change is an improvement.
**You:** The menu on mobile is fine but parts that mobile users don't need could be removed. The change that's been proposed isn't a good idea.

⇧ That is my summarization of the opinions on this topic. If I have misunderstood I'm sorry.

(Also, I'm not trying to poke fun or belittle you; I'm just trying to understand your side of things and see if there's a way to compromise.)

**Comment by TJScalzo** [comment]
I understand that you have accepted that this is an open source project @vaidaslamanauskas and I'm happy that you have. But I still want you to be happy with the site. I want to come to a compromise, not a concession. That's why I wrote the above post, to make you happy, not to be mean to you.

**Comment by meowwwls** [comment]
What about this? 

- nothing is hidden, but it takes up very little vertical space
- the icon is the link home, which frees up space for the rest of the menu items to be displayed without being cramped
- the animation runs once when the page loads, then the rays are hidden
- once again, it is not fixed, so it behave like the current menu in that sense
- bonus: no JavaScript

![mobile inline menu](http://res.cloudinary.com/meowwwls/image/upload/v1457834051/mobile-inline-io_fmjbcs.gif)

**Comment by TJScalzo** [comment]
That could maybe work as a compromise @meowwwls! Awesome!

**Comment by vaidaslamanauskas** [comment]
@meowwwls Great!

@TJScalzo I am fighting myself a bit in all this. But is all good. Have fun !

**Comment by TJScalzo** [comment]
Now @meowwwls, you just need to make a pull request and we'll be done with this issue!

**Comment by tholman** [comment]
wahoo! Great job everyone. Full on team effort.
