### ISSUE TITLE
Make a 404 page?

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#117]
There currently is no 404 page for this site. While I'm not sure how _necessary_ it is to have one, I think it'd be cool to have an interesting 404 page that matches what this site is about.

**Comment by JohJakob** [comment]
@TJScalzo Yeah, I totally agree. I have an idea already and make a draft tomorrow.

**Comment by TJScalzo** [comment]
Cool! :thumbsup:

**Comment by JohJakob** [comment]
![inspiring online 404](https://cloud.githubusercontent.com/assets/9888537/13443001/3f06dea6-dfff-11e5-94ec-9579c908870a.gif)

@tholman @TJScalzo What do you think?

**Comment by tholman** [comment]
<3

If we center it vertically, and have "Hey there!, It looks like there's nothing to be found here." I'm 100% in.

I love that little logo dude so much.

Little hover is a beautiful touch too!

**Comment by TJScalzo** [comment]
That looks amazing! I'm excited to see it on the website!

**Comment by JohJakob** [comment]
@tholman @TJScalzo OK, I'll center it vertically and change the text. The animation from the white to black background will be a bit smoother.

**Comment by tholman** [comment]
You're the best! Any text will do really. "looks like here's nothing to discover" just felt a bit weird.

**Comment by JohJakob** [comment]
@tholman What about "explore"?

**Comment by tholman** [comment]
You call!
Was there "here's" part that got me off... don't say that too often.

**Comment by JohJakob** [comment]
@tholman Do you know a good method to center the whole thing vertically?

**Comment by tholman** [comment]
```.container {
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
}```

**Comment by JohJakob** [comment]
@tholman I tried that without a container. That's why it didn't work. Thanks!

**Comment by JohJakob** [comment]
@tholman @TJScalzo Commited. I centered it vertically on devices with `min-height: 737px`, because it gets cropped on mobile devices otherwise.

**Comment by krikmo** [comment]
> I love that little logo dude so much.

YES, he's the best!

**Comment by TJScalzo** [comment]
>> I love that little logo dude so much.

>YES, he's the best!

I have to agree, he's really awesome! But why isn't he used as the favicon? Was it scaling issues?

**Comment by JohJakob** [comment]
@TJScalzo The favicon is too small. It would be a pixel mess.

**Comment by TJScalzo** [comment]
Ah, that makes sense. :thumbsup:
