### ISSUE TITLE
Favicon has background

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#121]
The globe has a square of white behind it. This means that when it shows up on a tab it looks a little strange. Should I make the changes myself or does someone else want to do it? (Like the person who made it in the first place.)

**Comment by JohJakob** [comment]
@TJScalzo I'll do it tomorrow. Despite that I wanted to redraw it to be pixel-perfect.

**Comment by JohJakob** [comment]
I've updated the favicon and the Pinned Tab Icon for Safari. The favicon doesn't have a white background anymore, but what about dark user interfaces in browsers (e.g. Google Chrome with dark theme or Firefox Developer Edition)?

**Comment by TJScalzo** [comment]
Oh, I didn't think of that... Maybe the black could be _outlined_ in white, rather than an entire background?

**Comment by JohJakob** [comment]
@TJScalzo Yeah, I thought about that too… Let's see…

**Comment by JohJakob** [comment]
@TJScalzo Done

**Comment by JohJakob** [comment]
@TJScalzo I removed the white outline because it looked like garbage.

**Comment by TJScalzo** [comment]
I'm not sure what should be done then...

**Comment by JohJakob** [comment]
@TJScalzo We should leave it black for now. The majority has light gray browser user interfaces.

**Comment by TJScalzo** [comment]
Makes sense. :+1:
