### ISSUE TITLE
[proposal] - Polygon shreader

### ISSUE THREAD

**Issue by tholman** [tholman/inspiring-online#125]
https://www.clicktorelease.com/code/polygon-shredder/

And then the amazing forks

http://alteredqualia.com/tmp/solitaire/
http://zz85.github.io/explorer-crasher/

**Comment by TJScalzo** [comment]
These are amazing! Would they get posted separately or all together? I think all in one post could work if the image were made to be a blend of the three.

**Comment by tholman** [comment]
All together, for sure.

We can have extra images in the post, if need be.

**Comment by TJScalzo** [comment]
@JohJakob I feel like the type for this shouldn't be WideWeirdWeb. It seems like it'd fit more with Coding or Beautiful. Does that make sense?

**Comment by JohJakob** [comment]
@TJScalzo Yeah, Coding would fit. I'll change it.
