### ISSUE TITLE
More types of posts

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#133]
### Currently there are five post types:
- Inspiration
- WideWeirdWeb
- Talk
- Resource
- An idea

Of those types, the last three have only been used once. I feel like there are existing posts that could be classified as something other than "Inspiration".

### Some ideas:
- Beautiful
- Coding
- Fun Facts!
- Typography
- CSS

I'm not sure if this is _needed_ but I think it'd be cool to be able to sort posts by type and, right now, that would result in two really big lists and three really short ones. The first step in making a sort view is making more detailed types.

**Comment by JohJakob** [comment]
@TJScalzo I didn't even know the last three types. We definitely need some more.

**Comment by TJScalzo** [comment]
@JohJakob the last three are from earlier posts. "An idea" is actually from the first post where @tholman introduced the website.

But what do you think of my ideas? Do you have any of your own? Are there posts whose type you think could be changed to something more specific?

**Comment by tholman** [comment]
This is awesome!

The tags were kind of a preemptive look at some stuff that would be cool in
the future, nows definitiely s good time to look at them.

Feel like we can do a lot here, happy to hear ideas before. Pitch in!!!


On Friday, March 4, 2016, Tim Scalzo <notifications@github.com> wrote:

> @JohJakob <https://github.com/JohJakob> the last three are from earlier
> posts. "An idea" is actually from the first post where @tholman
> <https://github.com/tholman> introduced the website.
>
> But what do you think of my ideas? Do you have any of your own? Are there
> posts whose type you think could be changed to something more specific?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tholman/inspiring-online/issues/133#issuecomment-192255066>
> .
>


-- 
Tim Holman
tholman.com

**Comment by vaidaslamanauskas** [comment]
I think we might need something for CodePen posts. Lots of cool stuff there. Maybe embed + special tag.

**Comment by TJScalzo** [comment]
@vaidaslamanauskas that would be a good tag/type to use.

I know that we can use for-loops using Liquid to get all of the posts of one type. I'm not sure how that could be implemented though.

**Comment by JohJakob** [comment]
@TJScalzo Your ideas are great!

**Comment by JohJakob** [comment]
![bildschirmfoto 2016-03-04 um 20 16 13](https://cloud.githubusercontent.com/assets/9888537/13537646/27dcd728-e246-11e5-9974-f432a1e6170e.png)

I'd place the post's type there. It could act as a link to a page with all posts of the same type. Also, I would define a specific color for each type.

**Comment by JohJakob** [comment]
We should put all "not-so-important things" like the tags that can be used in the Wiki.

**Comment by TJScalzo** [comment]
Alright, so what tags do we have?
- Inspiration
- WideWeirdWeb
- Talk
- Resource
- Technolgoy
- CodePens
- Typography

Should I or do you, want to start making an infrastructure-y thing for this idea, @JohJakob?

**Comment by JohJakob** [comment]
@TJScalzo You can do it :dancer:

**Comment by JohJakob** [comment]
Shall I start the wiki?

**Comment by TJScalzo** [comment]
Sure @JohJakob!

**Comment by JohJakob** [comment]
@TJScalzo I would add something like "CSS Madness" as well.

**Comment by TJScalzo** [comment]
#### Here is the list of types I'm working off of:
- Talk
- Resource
- Coding
- CodePen
- Typography
- CSS Madness
- Beautiful

**Comment by TJScalzo** [comment]
Another thing that should be done once this is implemented is changing the instructions to tell people their proposals need to have a type that they think the site would match with.
