### ISSUE TITLE
Redundant "Join in?" link

### ISSUE THREAD

**Issue by JohJakob** [tholman/inspiring-online#134]
We have the GitHub Corner on Inspiring Online now, so the "Join in?" link in the menu is redundant as it points to GitHub too, but the GitHub Corner doesn't tell a visitor (without experiences in open source development) that he can contribute to the blog in the first place. What do you think? Shall we keep the link?

**Comment by TJScalzo** [comment]
We could maybe add a tooltip to the GitHub Corner that concisely says you can join in/contribute to the site.

**Comment by JohJakob** [comment]
@TJScalzo That's a nice idea.

**Comment by tholman** [comment]
I like the join in, really... open to anyone who doesn't know github. But also links to the instructions.

Either way, not hurting anyone.
