### ISSUE TITLE
create a twitter bot

### ISSUE THREAD

**Issue by Haroenv** [tholman/inspiring-online#137]
It would be interesting to be able to follow interesting.online on twitter. Since there already is an xml feed, this should be doable, no?

I don't have experience in how to build this yet, so I don't know how much work it'd be.

**Comment by JohJakob** [comment]
@Haroenv Yeah, cool idea!

**Comment by vaidaslamanauskas** [comment]
definitely :+1:

**Comment by Haroenv** [comment]
https://github.com/housed/feedr and https://gitlab.com/hughr/rss-twitter-bot seem like easy choices, after quickly skimming

**Comment by Haroenv** [comment]
or what I'd looked over earlier, IFTTT seems to be even more straight-forward.

**Comment by JohJakob** [comment]
@Haroenv Why did you choose *inspiring_onlin* and not *inspiring_online*?

**Comment by Haroenv** [comment]
Because that's too much characters, and without underscore is already taken.

**Comment by JohJakob** [comment]
@Haroenv What about *InspiringWeb*?

**Comment by Haroenv** [comment]
That one's taken as well

**Comment by JohJakob** [comment]
@Haroenv Oh…

**Comment by JohJakob** [comment]
@Haroenv …but *inspiring_web* is not taken.

**Comment by tholman** [comment]
Was actually pretty close to having this set up too (with IFTTT)

used - https://twitter.com/nspiringOnline

**Comment by vaidaslamanauskas** [comment]
I think nspiringOnline is fine.

**Comment by Haroenv** [comment]
So I guess now we'll need a new post to test if the bot works, then we can decide further about the name (I also like @tholman's idea better than mine). My IFTTT rule is active.

**Comment by TJScalzo** [comment]
I like Nspiring_Online a little bit better than inspiring_onlin because it has the full site name technically. Also, it's owned by @tholman, the owner of the site.

**Comment by TJScalzo** [comment]
@tholman and @Haroenv, should I make a new post to see if the tweet bot works? I might not be able to right now but I probably could by the end of the day tomorrow.

**Comment by JohJakob** [comment]
@tholman Here's a profile image for *Nspiring_online*:

![inspiring online icon](https://cloud.githubusercontent.com/assets/9888537/13561888/53ec61c4-e432-11e5-9ecc-41b052b00986.png)

**Comment by JohJakob** [comment]
@Haroenv The bot doesn't work…

**Comment by TJScalzo** [comment]
> @Haroenv The bot doesn't work…

The bot that @tholman made also doesn't seem to work...

**Comment by tholman** [comment]
Haha, I haven't made it yet, just registered the account.

**Comment by TJScalzo** [comment]
Ah, I guess I misunderstood what you said. Sorry, @tholman.

**Comment by tholman** [comment]
Ok, set up ifttt, https://twitter.com/NspiringOnline ... will see how it goes. If it doesn't work, it'll probably be something we need to add to the rss feed data.

**Comment by JohJakob** [comment]
@tholman It seems to work :tada:

**Comment by TJScalzo** [comment]
Although it doesn't have an image. Would it be possible to add it to future tweets?

**Comment by Haroenv** [comment]
Yes. I saw that option when setting ifff up. 

Haroen Viaene

**Comment by tholman** [comment]
Ahh neat. Will have to edit the feed code or something to give back an image (doesn't currently) ... shouldn't be too tricky!

**Comment by JohJakob** [comment]
@tholman Would you give me access to the accounts needed for the bot? I'd like to see whether I could add some features to it (also for coming features like *Categories*).

**Comment by tholman** [comment]
@JohJakob Sure thing... shoot me a personal email, and I'll get you the details!

**Comment by TJScalzo** [comment]
@JohJakob / @tholman I've messed around with IFTTT a little bit and I think [this](https://cloud.githubusercontent.com/assets/15825214/15163724/352b489e-16d8-11e6-8c65-62bb85834e0c.png) would work so that the an image gets posted as well. (This is assuming you picked the option that posts a tweet **with a photo**.) (If you want, #InspiringOnline could also be included in each tweet as shown in the linked picture.)

Also, the `feed.xml` file would need to be edited so that the category can be included with a hashtag as was mentioned [here](https://github.com/tholman/inspiring-online/pull/188#issuecomment-216363888). I'm not really sure how much would need to be done to include it but I thought I'd mention it here so that it's not forgotten.

**Comment by JohJakob** [comment]
@tholman Did you get my mail?

**Comment by Haroenv** [comment]
I guess this is solved now, should it be closed?

**Comment by TJScalzo** [comment]
@Haroenv I'm not sure. It seems like @JohJakob wants to do some work on it still.

**Comment by tholman** [comment]
Sorry, yeah, keep it open. Its all on me getting back to @JohJakob ... got your email, out doing a couple of conferences and behind on everything. Always brief with the emails, since I'm mostly mobile. 

We'll get there! My bad!!!

**Comment by JohJakob** [comment]
@tholman No problem!

**Comment by tholman** [comment]
I might have added the images now... just need to wait for a tweet to confirm.

**Comment by tholman** [comment]
Haha, holy shit. Finally did it! 💃
