### ISSUE TITLE
[proposal] - Flat guitars

### ISSUE THREAD

**Issue by tholman** [tholman/inspiring-online#150]
Oldie but a goodie
http://www.flatguitars.com/

**Comment by TJScalzo** [comment]
This seems cool. Do you want me to write a post for this?

**Comment by tholman** [comment]
Would be awesome!

Everything's up for grabs here :D

Looking forward to being back from holidays, to get back into it as well.

**Comment by vaidaslamanauskas** [comment]
Lovely to see that it is growing. Slowly but surely :)
