### ISSUE TITLE
[proposal] pixel

### ISSUE THREAD

**Issue by Haroenv** [tholman/inspiring-online#153]
http://essenmitsosse.de/pixel/

**Comment by JohJakob** [comment]
@Haroenv Wow, this is neat!

**Comment by TJScalzo** [comment]
@Haroenv what type would this fit under?

**Comment by Haroenv** [comment]
I'm writing it now :smile:

**Comment by TJScalzo** [comment]
@Haroenv, is "pixel" not capitalized for a reason? Because normally titles have their first letter capitalized. I just wonder because, as far as I can see, there's no specific reason for it not to be capitalized.

**Comment by Haroenv** [comment]
I guess it would indeed be better with a capital letter

**Comment by tholman** [comment]
Hey, the post appeared!

Love it, with the gif. Its awesome when we're super up to date with a new post, right when something comes out. Gotta get myself onto that more often!

**Comment by TJScalzo** [comment]
@Haroenv shall I make the changes or would you like to?

**Comment by Haroenv** [comment]
You should do it, I'm in bed :wink:

**Comment by TJScalzo** [comment]
Okay, I'm working on it now.
