### ISSUE TITLE
Black lightbulb of 404 error page is not visible in Internet Explorer

### ISSUE THREAD

**Issue by JohJakob** [tholman/inspiring-online#161]
Before the transition from black to white, the lightbulb is not visible in Internet Explorer. Only the rays are visible.

![wp_ss_20160311_0002](https://cloud.githubusercontent.com/assets/9888537/13709334/a9d49d70-e7b3-11e5-926a-69c694a4318e.png)

**Comment by tholman** [comment]
Anyone know whats up with this one? I can't really test, but its got to be something super small.

**Comment by JohJakob** [comment]
@tholman Yeah, it's a really small issue. I'll try to fix it when I have some time.
