### ISSUE TITLE
What's up with posts not appearing?

### ISSUE THREAD

**Issue by vaidaslamanauskas** [tholman/inspiring-online#163]

**Comment by JohJakob** [comment]
@vaidaslamanauskas Hmm… It takes a while, but it's been a while since I wrote the last post.

**Comment by vaidaslamanauskas** [comment]
It should be almost instant. There's definitely some sort of problem here.

**Comment by TJScalzo** [comment]
I've looked the post over and I can't seem to find anything wrong with it other than the front matter being in a different order than normal and that shouldn't make it not show up. It's odd...

**Comment by TJScalzo** [comment]
Another odd thing that's happened is the post shows up when testing locally but not on the live page.

**Comment by JohJakob** [comment]
@TJScalzo I used the order @tholman used when I started.

**Comment by TJScalzo** [comment]
I guess I meant different from what _I_ consider normal. It almost definitely doesn't matter and so I don't know what could be causing it to not show up.

**Comment by Haroenv** [comment]
FWIW, the design change showed up immediately

**Comment by JohJakob** [comment]
@Haroenv I have no idea… Maybe @tholman can help us.

**Comment by TJScalzo** [comment]
The Staggering Beauty post now shows up on the site. I don' know why...

**Comment by tholman** [comment]
Weird about the posts showing up. I'm looking into it now, very curious, since its an automatic github thing.

**Comment by vaidaslamanauskas** [comment]
So, is it something to do with the date?
@tholman I think you figured something.

**Comment by TJScalzo** [comment]
Are the commits 7c3ca02, 0a3b5fd, and 6c1abfd meant to try and fix this issue @vaidaslamanauskas?

**Comment by vaidaslamanauskas** [comment]
Yeah. Trying to figure out what's happening.

**Comment by TJScalzo** [comment]
That last one seems to have fixed it.

**Comment by TJScalzo** [comment]
Fun.css at least shows up on the home page now! So that's good!

**Comment by vaidaslamanauskas** [comment]
Yea. It kinda works now. But I still can't wrap my head around it. 
The closest I came. There is something wrong with jekyll-paginate and date and timezone. Jeez
:)

**Comment by TJScalzo** [comment]
Could it be that the post's time is considered to be in the future for the server because its timezone is weird? And so _locally_ it works since our computers have the correct time but the server thinks the time/date is something completely different?

**Comment by vaidaslamanauskas** [comment]
Yeah. Something like that.

**Comment by tholman** [comment]
I feel like this's been good again... right? Going to close this off for now. Lets open the second we see it again.
