### ISSUE TITLE
[proposal] - Kandinsky

### ISSUE THREAD

**Issue by woodylama** [tholman/inspiring-online#166]
https://musiclab.chromeexperiments.com/Kandinsky

**Comment by TJScalzo** [comment]
This is a specific experiment from a collection of experiments. The _collection_ was proposed in #156. I feel like the entire collection should be a post instead of one specific experement from that collection. Let me know what you think @vaidaslamanauskas and @Haroenv.

**Comment by Haroenv** [comment]
I think it's worthwhile to post both the collection and individual things (but not all of them) at different times

**Comment by tholman** [comment]
Closing these off... mainly cuz they're old things now.
