### ISSUE TITLE
[proposal] - jor.dance

### ISSUE THREAD

**Issue by Haroenv** [tholman/inspiring-online#170]
http://jor.dance/

**Comment by TJScalzo** [comment]
I will make a pull request for this.

**Comment by TJScalzo** [comment]
Question: What type should I put it under?

**Comment by tholman** [comment]
Inspiration, Coding I guess... or make something new! :D Portfolio perhaps

On Wed, Apr 13, 2016 at 5:48 PM, Tim Scalzo <notifications@github.com>
wrote:

> Question: What type should I put it under?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tholman/inspiring-online/issues/170#issuecomment-209662562>
>



-- 
Tim Holman
tholman.com

**Comment by TJScalzo** [comment]
Is it possible/allowed to use two types? If so I'd use Inspiration and Coding. If not I think Inspiration works best.
