### ISSUE TITLE
[proposal] - lock the taskbar

### ISSUE THREAD

**Issue by Haroenv** [tholman/inspiring-online#171]
https://madeupandprobablydoesnotexist.com/taskbar/

**Comment by TJScalzo** [comment]
I actually feel like the main page of that website is much more interesting. It's a dancing emoticon with music! I don't know, but I feel like that fits this website better? Maybe?

**Comment by TJScalzo** [comment]
Now that I look back at this, why not use both? The homepage and /taskbar are completely separate from each other, they simply share a url.

**Comment by tholman** [comment]
Closing these off... mainly cuz they're old things now.
