### ISSUE TITLE
GitHub Corner is positioned oddly on Mac

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#172]
I noticed today that the GitHub Corner is positioned underneath the scrollbar in Safari. I'm not sure why that is or if it happens in other browsers.
#### Here's a screenshot:
![screen shot 2016-03-17 at 9 39 20 pm](https://cloud.githubusercontent.com/assets/15825214/13866169/189086dc-ec89-11e5-98a1-0bdd2037862d.png)

**Comment by TJScalzo** [comment]
It doesn't happen on Google Chrome.
![screenshot 2016-03-22 at 2 13 34 pm](https://cloud.githubusercontent.com/assets/15825214/13962657/5aa54302-f038-11e5-8b5f-771aafc0cf6e.png)

**Comment by tholman** [comment]
<img width="219" alt="screen shot 2016-03-22 at 2 23 09 pm" src="https://cloud.githubusercontent.com/assets/794999/13962964/bd0223ca-f039-11e5-9305-e211ef3608b7.png">

Safari for me. We should probably close as "wont fix" ... don't want to mess around with browser detection etc... would just be a pain.
