### ISSUE TITLE
[proposal] - Rhyming URL shortener using the 5000 most common english words. 

### ISSUE THREAD

**Issue by traghav** [tholman/inspiring-online#184]
Check out [http://trim.kim](http://trim.kim)

It does count as self promotion though, I made it, bummer. If it helps, I am not promoting myself anywhere on the site. Eitherway feedback appreciated!

**Comment by tholman** [comment]
Thanks for the submission. Yeah, does count as self pro-mo! Sorry, gotta be strict :(

**Comment by TJScalzo** [comment]
@traghav even though it won't be on the site I'd like to let you know that it's very cool. I think it's an interesting concept.

**Comment by Haroenv** [comment]
Yeah, I quite like it too, despite being self-made and we can't show it
