### ISSUE TITLE
[proposa] - typedrummer

### ISSUE THREAD

**Issue by JohJakob** [tholman/inspiring-online#186]
[typedrummer](http://typedrummer.com)

**Comment by TJScalzo** [comment]
I like this one. It's very simple but also seems like fun.

**Comment by TJScalzo** [comment]
Here are some screenshots for who ever wants to write the post for this one. (I'm busy but I thought I'd help out by taking some screenshots.)
![screen shot 2016-05-17 at 2 47 58 pm](https://cloud.githubusercontent.com/assets/15825214/15335017/8cd0b30c-1c3e-11e6-88b0-f60aacfaff54.png)
![screen shot 2016-05-17 at 2 47 08 pm](https://cloud.githubusercontent.com/assets/15825214/15335018/8cd51eb0-1c3e-11e6-9a40-5c5d8e8a94c3.png)
As I said before, I like this one. So if you don't want to do this one, @JohJakob, I'm willing to.
