### ISSUE TITLE
404 doesn't work on subdomains

### ISSUE THREAD

**Issue by Haroenv** [tholman/inspiring-online#191]
I guess the css gets linked relatively, because for example <http://inspiring.online/some/page/that/doesnt/exist> shows a broken 404 page.

**Comment by JohJakob** [comment]
@Haroenv Thanks! I [fixed](https://github.com/tholman/inspiring-online/commit/74e82f1c24abf2cfcc92fcaacee1ec575d0c5b0b) it.

(Apparently, it is the 404th commit 😄)

**Comment by Haroenv** [comment]
Wouldn't it be better to link to either `//` or simply `/`?

**Comment by JohJakob** [comment]
@Haroenv Yeah, you're right.
