### ISSUE TITLE
Links don't work while on forks

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#193]
If you go to my fork of tholman/inspiring-online [here](http://tjscalzo.github.io/inspiring-online/) you'll notice that nothing is styled correctly because of the fact that the CSS is linked using a root style of link that expects the files to be coming from the base of the URL.
This issue was noticed [here](https://github.com/tholman/inspiring-online/pull/188#issuecomment-216058473) by @Haroenv and I've been thinking about how to fix it since. I think I have a solution; I'll submit a pull request soon.

**Comment by Haroenv** [comment]
The problem  is that you can use `/` in the real site, but in forks, those assets get to the root of that site, which isn't right.

**Comment by TJScalzo** [comment]
Yeah... I thought I using /inspiring-online before it would work. Am I at least on the right track? Sort of?

**Comment by Haroenv** [comment]
Then that wouldn't work on the live site

**Comment by TJScalzo** [comment]
I didn't replace the originals; I just more links with the altered href.

**Comment by Haroenv** [comment]
Aha, great idea!

**Comment by TJScalzo** [comment]
The code is this:
```CSS
<link href="/css/stylesheet.css" rel="stylesheet" type="text/css">
<link href="inspiring-online/css/stylesheet.css" rel="stylesheet" type="text/css">
```

**Comment by TJScalzo** [comment]
But the altered link I used didn't work.

**Comment by TJScalzo** [comment]
@Haroenv do you think this would work?
```css
<link href="/css/stylesheet.css" rel="stylesheet" type="text/css">
<link href="//inspiring.online/css/stylesheet.css" rel="stylesheet" type="text/css">
```

**Comment by Haroenv** [comment]
use 

```css
<link href="/inspiring-online/css/stylesheet.css" rel="stylesheet" type="text/css">
```

**Comment by TJScalzo** [comment]
Hm... That didn't work. Should I try what I suggested above, @Haroenv?

**Comment by TJScalzo** [comment]
Or even without the two slashes:
```css
<link href="inspiring.online/css/stylesheet.css" rel="stylesheet" type="text/css">
```

**Comment by Haroenv** [comment]
You're option should also work.

**Comment by Haroenv** [comment]
The slashes aren't optional, they mean that you look on another site.

**Comment by TJScalzo** [comment]
I was too quick to assume your idea hadn't worked. Which option is better though, mine or yours? Do we want the fork to look at the CSS that it has or the most up to date CSS?

**Comment by Haroenv** [comment]
It's better not to rely on `inspiring.online` to be online, so my original idea should work best.

**Comment by TJScalzo** [comment]
One problem that we run into is that every asset now needs to be updated to have this second link. Would it be possible to automatically prepend `/inspiring-online` to every interior link? I feel like that's a bit of a stretch but it'd be cool if there was an easy way to do that.

**Comment by Haroenv** [comment]
You could, but then you'd need to write that method every time, I think it'd be best to now write it on the (10, 20, idk) places it's there and take care to add them when necessary.

**Comment by TJScalzo** [comment]
Another problem is every page other than the homepage requires the `/inspiring-online` in front of it but all the links are setup so that they lead to the root of the page.

**Comment by Haroenv** [comment]
Technically defining links from the root or relative shouldn't make any difference.

What could be an option is that in `_config.yml` you add a variable like `baseurl` which you set to `/inspiring-online` on forks and `/` on the real site (make sure not to have pull requests featuring that) and then edit all the links to `{site.baseurl}/css...`

**Comment by TJScalzo** [comment]
That's a good idea. But how would you make it so that the main site doesn't receive the changes to the `_config.yml`?

**Comment by Haroenv** [comment]
Annoying, but [this](http://stackoverflow.com/questions/28703140/github-pull-request-ignore-some-file-changes) is how you do that.

**Comment by TJScalzo** [comment]
So like, every time someone with a fork makes changes they'd have to copy all of their changes to a different branch excluding the `_config.yml` and make a pull request from there? Did I understand that right?

**Comment by Haroenv** [comment]
Yes, but that's only if they want their fork to be visible on github pages. Regular changes could be seen in the code alone too.

**Comment by TJScalzo** [comment]
I feel like that's a lot of work to go through for something that people on the site won't even see. Maybe instead of having the `baseurl` variable permanently changed on the forks it could be changed when it's needed to show people what's happening? Basically, it'd be there for when it's needed but people don't need to go through the trouble of making it always work.

**Comment by Haroenv** [comment]
Yes, that's an idea, you could set it when you want to see it on your fork, but set it back to `/` when you want to do a pull request

**Comment by TJScalzo** [comment]
Cool, I'll set up the infrastructure for that. Should I keep the extra links for the assets or should they also be changed to use the `baseurl` variable?

**Comment by Haroenv** [comment]
Extra links isn't very pretty I think, I'd go for a var in `_config.yml`

**Comment by TJScalzo** [comment]
Okay, I've changed everything but in testing the site I've gotten some errors. 
![screen shot 2016-05-16 at 4 21 25 pm](https://cloud.githubusercontent.com/assets/15825214/15302704/4e7b7356-1b82-11e6-8814-3f4a97e4bcce.png)
I've set the `baseurl` to '/' and I've replaced all of the asset links to something along the lines of 
```html
<img src="{{ site.baseurl }}assets...
```
I'm not quite sure what I've messed up. Help @Haroenv?

**Comment by TJScalzo** [comment]
Wait
I think I know the problem.

**Comment by TJScalzo** [comment]
Never mind, I forgot to restart Jekyll so that it would use the new `_config.yml`.

**Comment by TJScalzo** [comment]
Alright
Now I think I'm going to update the `README.md` to include more information about maintaining a fork and having things work properly on the github page of that fork.

**Just so that I've said it somewhere, the `baseurl` variable should be replaced with `/inspiring-online/` when someone wants things to work on a fork.**

**Comment by Haroenv** [comment]
not `{{base.url}}`, `{{site.baseurl}}`

**Comment by TJScalzo** [comment]
@Haroenv Did I leave one of those in? I accidentally started changing them to `{{base.url}}` and then realized my mistake. Did I forget to change one of them to `{{site.baseurl}}`?

**Comment by Haroenv** [comment]
https://github.com/TJScalzo/inspiring-online/commit/3be5dd541fb462f18cdde0b19429a93597fba113#commitcomment-17494208

**Comment by tholman** [comment]
Checking in, dd that fix it? 💃

**Comment by Haroenv** [comment]
@tjscalzio is still busy with it afaik, but now it's just writing a bit in readme

**Comment by TJScalzo** [comment]
@tholman @Haroenv I'm a little busy so I might not finish this right away. I'll try to be done soon though.

**Comment by TJScalzo** [comment]
Alright, I've done it. I feel like I wrote way too much. Let me know what you think @tholman and @Haroenv.

(BTW: Would it be good to also have this information in the wiki? Should the info in the wiki be in the README? Are they meant to overlap like this?)

**Comment by JohJakob** [comment]
@TJScalzo The basic stuff is in the README and more in-depth information are in the Wiki. I would add your details about forks and baseurl to the Wiki.

**Comment by Haroenv** [comment]
Agreed with @JohJakob, some of that text shouldn't be in the README but in the wiki (but a mention that there's a wiki and a link to it)

**Comment by JohJakob** [comment]
@TJScalzo @Haroenv I'll put your information in the Wiki and add a link to it in the README.

**Comment by JohJakob** [comment]
OK, I added the page '[Forks and Pull Requests](https://github.com/tholman/inspiring-online/wiki/Forks-and-Pull-Requests)' to the Wiki.

**Comment by JohJakob** [comment]
@TJScalzo [Here](https://github.com/TJScalzo/inspiring-online/pull/7) are the changes for the README.
