### ISSUE TITLE
Images are nuts

### ISSUE THREAD

**Issue by tholman** [tholman/inspiring-online#194]
Its more or less impossible to clone this repo now due to image size. More or less, I'm 99% sure that the solution will be for me to take a bunch of images, and host them in my own hosting, and absolutely link them within inspiring.online ... And then do this every few months to keep things down.

Makes sense right... there's not really another way people do this?

**Comment by Haroenv** [comment]
Maybe host them in a separate repo, but then that one would be so large.

**Comment by tholman** [comment]
Yeah... it doesn't matter so much if they're hosted by me, I can absorb the cost to a fair degree. And they can still be accessible to forks and what-not. Seems ok. More important that people can contribute... I'd say its almost impossible now, I'd not wait that long for anything to download 💃

**Comment by Haroenv** [comment]
How would you see asking new images, manually by you?

**Comment by tholman** [comment]
I imagine, leaving a few in the repo... I can move them over 10 at a time (or at the moment, whenever I get time!) ... so new live in the repo, and legacy get moved from time to time.

Doesn't clog things up... perhaps a tiny docs article just in case.

**Comment by JohJakob** [comment]
I like the idea of hosting the images separately. Maybe, we could create a small web portal where contributors can upload the image for their article (with a maximum file size etc.) and retrieve its URL for the front matter.

**Comment by Haroenv** [comment]
Great solution @tholman
