### ISSUE TITLE
Sort by author?

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#205]
I could do the same thing that I did with categories with authors/contributors. It'd make it possible for a user to view all of the posts that one person has added to the site. I'm not sure how usable or wanted this would be. But I'd like to put the possibility out there.

**Comment by JohJakob** [comment]
@TJScalzo It's a nice idea, but I think it's not necessary.

**Comment by TJScalzo** [comment]
@JohJakob ok, I just wanted to make sure someone saw this before I closed it.
