### ISSUE TITLE
Add links to social media?

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#212]
Right now, the only way people would know we have a twitter is by going onto Github and seeing the issue or if they follow one of us who retweet posts by the account. I have no idea how they'd ever find out we have a Facebook page.

How might we be able to advertise the Twitter and Facebook pages in a way that isn't super intrusive?

**Comment by TJScalzo** [comment]
No one's responded to this and I'm not sure why...

**Comment by JohJakob** [comment]
@TJScalzo Sorry! I would put the links at the bottom of the page. If everyone agrees, I'll do it.

**Comment by TJScalzo** [comment]
Through the redesign, a link to the twitter page was added. Should a link to the Facebook page be added as well?

**Comment by tholman** [comment]
If it runs off ifttt, then yep, why not 💃

**Comment by TJScalzo** [comment]
Hm... It seems like whatever was running the Facebook page has stopped working. I didn't set it up so I can't fix it. It looks like @JohJakob made it, so he'll have to look into that.

**Comment by JohJakob** [comment]
@TJScalzo Actually, it runs on nothing. I'm writing the posts by hand. I'll add the new posts tomorrow. If we can expect more posts, I'll look if I can make it automagically.

**Comment by TJScalzo** [comment]
I'm going to close this. The Twitter account is linked and the Facebook page doesn't work automatically. Since it relies on a person manually writing posts for it, I don't think it needs to be linked to.
