### ISSUE TITLE
Re-add random, categories, and/or 404 page?

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#217]
It could be said that random isn't really needed since it's now really easy to go through all the posts. However, it doesn't add to load time so why not just let it exist? Categories could still be useful for people who want to see posts in one specific topic.

Or, we could maybe try using tags? So rather than having a page with all the categories on it, each post tile would have tags at the bottom of it that can be clicked to go to a page with posts tagged with that tag.

**Comment by TJScalzo** [comment]
Also the 404 page, that should definitely be added back in.

**Comment by tholman** [comment]
Yeah, I pulled everything out because it was just faster to rebuild that way... (including some things we should probably get back, like html compression)

I've kept the categories in the post data... but I kind of feel comfortable leaving this alone for 6 months or so, and see how much this new post format keeps the post rates up (I can see myself doing multiple posts a day now, compared to 1 ... or 2)

**Comment by tholman** [comment]
Yeah, 404 needs to come back (again, sorry!) ... I'd almost be content with it just redirecting straight to `/` ... but the other one was super nice too! 💃

**Comment by JohJakob** [comment]
Tomorrow, I'll redesign the logo, make a new 404 page and add some posts. We should call the redesign the v2 release. I'd also make a little thingy for feature announcements and so on. I'll design something for that.

**Comment by TJScalzo** [comment]
I feel like the random page could be added in with very little impact on the rest of the site. It's just a redirect page so it shouldn't effect anything loading-wise. I can quickly add it back in unless someone thinks it'll clash with the idea behind the site.

**Comment by JohJakob** [comment]
Heyo! I'm back… finally.
Well, the logo redesign was not successful so far, but I will think about it and a new 404 page matching the current website design.

**Comment by Haroenv** [comment]
Kinda related to this, the `splitHERE` hack might not needed if you use the `{{ something | jsonify}}` filter @tholman

**Comment by tholman** [comment]
ooh... going to close this. (404 redirecting to / is better for us) ... the jsonify thing though, I'm still interested in... I couldn't get it all working :/
