### ISSUE TITLE
[New design] not responsive

### ISSUE THREAD

**Issue by Haroenv** [tholman/inspiring-online#218]
To me it'd make sense if smaller screen sizes had resp. 2 and one column, instead of the minimum of 3 right now.

**Comment by tholman** [comment]
I thought it did this... looks fine on the emulators?

**Comment by Haroenv** [comment]
Oh yeah I'm sorry, only the Safari responsive viewer is sometimes picky when something is sized automatically. It looks more than fine on real devices.
