### ISSUE TITLE
Dynamic Contributors List from GitHub API

### ISSUE THREAD

**Issue by jackrugile** [tholman/inspiring-online#22]
It would be nice to keep the http://inspiring.online/contributors dynamically updated. This might add on too much complexity, but might be worth looking into.

**GitHub API Docs for listing contributors**
https://developer.github.com/v3/repos/#list-contributors

**Possible sub-issues with this**
1. I don't want to hit the API with each page load. I'm not sure how to go about writing to cache file with just JavaScript, I only know how to do it with PHP. Any ideas on keeping requests to the API down?
2. This feature might take away from the spirit of this repo, which is to get people involved with contributing code. I could see the satisfaction in getting a pull request merged, and then going to update your status on the contributors page. That might be a fun and rewarding process for people.

If this isn't in line with the repo's direction, feel free to close. Just a thought!

**Comment by mattdesl** [comment]
Good idea. Maybe just a simple build step during compile/bundle? It could export to a JSON containing the contributor names.

Example:

`contributors.js`

```js
var ghAuth = require('ghauth')
var ghApi = require('gh-api')

ghAuth({
  configName: 'gh-api',
  noSave: true
}, function (err, data) {
  if (err) throw err  
  ghApi('/repos/tholman/inspiring-online/contributors', {
    token: data.token
  }, function (err, data) {
    if (err) throw err
    var list = data.map(function (x) {
      return x.login
    })
    console.log(JSON.stringify(list))
  })
})
```

Then:

```sh
node contributors.js > contributors.json && build-site
```

**Comment by JohJakob** [comment]
See [this pull request](https://github.com/tholman/inspiring-online/pull/136).

**Comment by tholman** [comment]
Sticking with the manual stuff for now, just because api requests and whatnot.
