### ISSUE TITLE
Fallback to tell user JS is needed

### ISSUE THREAD

**Issue by Haroenv** [tholman/inspiring-online#221]
We should put a loop that shows *all* of the posts or paginated in a `<noscript>` block for progressive enhancement.

**Comment by tholman** [comment]
I thought this, but then also 99% of the actual links will be totally useless without javascript anyway...

**Comment by Haroenv** [comment]
That's a good point, didn't think of that.

**Comment by TJScalzo** [comment]
I still feel like there should be something there as a fallback in case someone visits the site and doesn't have JavaScript enabled. So I made [this](https://github.com/TJScalzo/inspiring-online/commit/36ae2c79baf491b2930ea99ab751a8db9645b214). I also made a [pull request](https://github.com/tholman/inspiring-online/pull/222).

**Comment by TJScalzo** [comment]
This was resolved in 0464e6a.
