### ISSUE TITLE
KatLeidoscope site no longer exists

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#225]
The website that the post KatLeidoscope links to no longer exists. Should the post be deleted?

**Comment by tholman** [comment]
I kind of like this historic archive... perhaps something on the post that marks it as "gone"

**Comment by TJScalzo** [comment]
The text could be struck through and underneath say that it's gone?
Maybe the image could be greyed out as well?

**Comment by tholman** [comment]
Yeah, should give it 50% opacity, and lay on `pointer-events: none;`

**Comment by TJScalzo** [comment]
Sounds good, I'll do that soon.
