### ISSUE TITLE
Some posts don't have post pages

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#226]
Once posts reach the third "page," they no longer have a post page. For example, [Jetlag](http://inspiring.online/jetlag) has a post page since it appears on the second "page" of the homepage. However, [Australia.css](http://inspiring.online/australia.css) doesn't since it's on the third "page." 

I'm not sure why that is or if I'm correctly understanding why the post pages don't exist. If anyone could shed some light on why this might be happening, I'd appreciate it very much.

**Comment by tholman** [comment]
Australia CSS does - http://inspiring.online/australiacss/
Some of the oldest do - http://inspiring.online/emotions-through-css/

... Are you sure they're not appearing for you?

**Comment by Haroenv** [comment]
When seeing that page, I saw that the Australia.css link didn't work since the ?ref that's being added has a dot, and thus it searches for Australia.css?ref=inspiring of the file type online. Maybe this should be changed to a dash instead?

**Comment by tholman** [comment]
Fixed that now... looks like it was because it actually needed the trailing slash, that we always delete ;) haha. Irons.

**Comment by tholman** [comment]
Anyhow... we all see the pages now, for these things? :)

**Comment by TJScalzo** [comment]
Ah, I guess I thought posts didn't have pages because I was typing the wrong transformation of the title, my mistake. I see them now.
