### ISSUE TITLE
[proposal] - I Look Like Barack Obama

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#233]
http://www.ilooklikebarackobama.com

It'd definitely fit under WeirdWideWeb. I'm just worrying that it's too weird? I don't know... I'd love a second opinion.

**Comment by Haroenv** [comment]
Delightfully weird

**Comment by tholman** [comment]
Lol, definitely weird. Doesn't really fall into the domain of a "good" site though, like some of the other weird shit 💃
