### ISSUE TITLE
Tiles position incorrectly

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#239]
![screen shot 2016-11-02 at 9 30 05 am](https://cloud.githubusercontent.com/assets/15825214/19930547/4afd46c2-a0df-11e6-9ac2-3a7f6bcf346a.png)
![screen shot 2016-11-02 at 9 30 37 am](https://cloud.githubusercontent.com/assets/15825214/19930646/c20d627e-a0df-11e6-8c1a-16d6be84ae7c.png)
I'm on Safari Version 9.0.3 (9537.86.4.4)

**Comment by TJScalzo** [comment]
The first issue occurs on page load and can be fixed by resizing the window. The second issue happens when in two columns.

I'll also note that the animation of the tiles as the move to new positions is very erratic. I'd post a video but I don't have the means to right now.

**Comment by tholman** [comment]
can anyone still reproduce this? Closing... but please open again.

**Comment by TJScalzo** [comment]
Yes, I can still reproduce it. But if no one else can I'm pretty sure it'll be fine. I have an "old" computer with a very out-of-date OS so it's probably just that.
