### ISSUE TITLE
Link for Eye of the Stormers is broken

### ISSUE THREAD

**Issue by lukekrikorian** [tholman/inspiring-online#241]
I'm pretty sure It redirects to Spotify homepage. Anyone else have this problem?

**Comment by TJScalzo** [comment]
This also happens for me. It seems like they've had it redirecting like that for a while.
Do you want to mark the post's front matter with `siteDown: true` @lukekrikorian?

**Comment by TJScalzo** [comment]
Just as point of reference, this is the post @lukekrikorian is talking about: [Link!](http://inspiring.online/eye-of-the-stormers/)

**Comment by lukekrikorian** [comment]
Front matter is  in _post, correct?

**Comment by TJScalzo** [comment]
@lukekrikorian, yes. You'd have to find the post file for the Eye of the Stormers. If you're unsure of how to edit the front matter check out [this page on the wiki](https://github.com/tholman/inspiring-online/wiki/Front-Matter).

**Comment by lukekrikorian** [comment]
Thanks! I've just made a pull request.

**Comment by TJScalzo** [comment]
Commit 39434a5 fixes this issue.
