### ISSUE TITLE
Older tiles don't load on a big screen / large browser window

### ISSUE THREAD

**Issue by trienow** [tholman/inspiring-online#251]
On my 2560x1440 monitor, not all tiles load, so that scrolling down to older tiles is not possible.
Resizing the browser window and scrolling down makes the older tiles load.

![Older tiles not loading on a large monitor](https://cloud.githubusercontent.com/assets/8478950/24245778/9603405a-0fc4-11e7-89ce-001b1e6bd54d.png)

**Comment by TJScalzo** [comment]
@trienow Reopen this if 038cbb1 didn't fix the problem (or if there's a better way of doing it).

**Comment by trienow** [comment]
It works, thanks 👍
