### ISSUE TITLE
[proposal] AutoDraw - Dan Motzenbecker and Kyle Phillips (Google Creative Lab)

### ISSUE THREAD

**Issue by Synj24** [tholman/inspiring-online#257]
> AutoDraw is a new kind of drawing tool. It pairs machine learning with drawings from talented artists to help everyone create anything visual, fast.

[autodraw.com](https://www.autodraw.com/)
[aiexperiments.withgoogle.com/autodraw](https://aiexperiments.withgoogle.com/autodraw)
[Dan Motzenbecker's site](https://oxism.com/)

**Comment by tholman** [comment]
Closing all the current issues, for a fresh start.
