### ISSUE TITLE
[proposal] Brick Block

### ISSUE THREAD

**Issue by nitinthewiz** [tholman/inspiring-online#259]
Cool 3D tile editor, in your browser

[Brick Block](http://oskarstalberg.com/game/house/index.html)
[Oskar Stalberg's Tumblr](http://oskarstalberg.tumblr.com/)

**Comment by JohJakob** [comment]
This is soooo cool!

**Comment by TJScalzo** [comment]
I think this is a great idea to post! You can make a pull request if you'd like.

**Comment by TJScalzo** [comment]
Closed by pull request #261
