### ISSUE TITLE
[proposal] Learning Music - Ableton

### ISSUE THREAD

**Issue by Synj24** [tholman/inspiring-online#260]
A nice introduction into learning the basics of songwriting which also allows you to experiment with musical elements in your browser.

[learningmusic.ableton.com](https://learningmusic.ableton.com/index.html)
[Ableton's site](https://www.ableton.com/en/)

**Comment by TJScalzo** [comment]
I think this is a great thing to post! You can make a pull request if you'd like to, @Synj24.
