### ISSUE TITLE
[proposal] What's Special About This Number?

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#265]
[What's Special About This Number](http://www2.stetson.edu/~efriedma/numbers.html) lists a mathematical fact about almost every number up to 9999.

I'm not really sure what the picture should be for this...

**Comment by Synj24** [comment]
Holy integers! this must of taken awhile.

In terms of images i threw a couple of ideas together. Not sure if they're any use... 
![whats-special-about-this-number-2](https://cloud.githubusercontent.com/assets/13753370/26212738/7181859c-3bee-11e7-83e7-82276d8705bd.png)


![whats-special-about-this-number-1](https://cloud.githubusercontent.com/assets/13753370/26212737/717ddc76-3bee-11e7-9dfb-d95e14893a94.png)

![whats-special-about-this-number-3](https://cloud.githubusercontent.com/assets/13753370/26212951/30b86854-3bef-11e7-8d5d-8b282b7e6d27.png)
