### ISSUE TITLE
[proposal] Narrow Design - Nick Jones

### ISSUE THREAD

**Issue by Synj24** [tholman/inspiring-online#267]
:snail: :shell:
Nick Jone's new portfolio site showcases a unique golden ratio scrolling interface.
_may be unsuitable for vertigo sufferers._

[narrowdesign.com](https://www.narrowdesign.com/)
[Nick Jone's Twitter](https://twitter.com/narrowd)

**Comment by tholman** [comment]
Closing all the current issues, for a fresh start.
