### ISSUE TITLE
[proposal] Defender of the Favicon - Mathieu Henri

### ISSUE THREAD

**Issue by Synj24** [tholman/inspiring-online#268]
A remake of the arcade game [Defender](https://en.wikipedia.org/wiki/Defender_(1981_video_game)) squished down into a favicon. 
Developed in 2008 so perhaps a bit to old to post?
:space_invader: :rocket:

[Defender of the Favicon](http://www.p01.org/defender_of_the_favicon/)
[Mathieu Henri](http://www.p01.org/)

**Comment by tholman** [comment]
Totally still good!

**Comment by Synj24** [comment]
Rad, I'll make a PR.
