### ISSUE TITLE
[proposal] Lifemap - Damien M. de Vienne (CNRS)

### ISSUE THREAD

**Issue by nibreh** [tholman/inspiring-online#274]
Exploring the Entire Tree of Life
http://lifemap.univ-lyon1.fr/

Made by: 
_Damien M. de Vienne is a CNRS researcher working at the Biometry and Evolutionary Biology Laboratory (LBBE) in Lyon (France). He developed Lifemap with the technical support of the Informatics Pole of the laboratory, in particular Stéphane Delmotte and Bruno Spataro._

**Comment by tholman** [comment]
Closing all the current issues, for a fresh start.
