### ISSUE TITLE
[discussion] Self-promotion/Posting personal work

### ISSUE THREAD

**Issue by JohJakob** [tholman/inspiring-online#292]
Usually, we don't accept posts with personal work/projects of the author, as stated in the [README](https://github.com/tholman/inspiring-online#what-we-dont-like):

> Please don't post your own things. I know self promoting is fun, but it's kind of against the spirit of what we're trying to do.

But because most of those submissions are pretty cool, we should discuss this "rule" and how strictly we should follow it.

I opened this issue regarding two recent submissions by @hectorbus and @Ananthavijay.

**Comment by Ananthavijay** [comment]
Thanks for opening this for me and can I work with u guys?

**Comment by Ananthavijay** [comment]
sorry i didn't read the  read me thats why I posted my  own work without knowing.

**Comment by JohJakob** [comment]
@Ananthavijay Of course, you can work with us! This repo is for everyone.

**Comment by Ananthavijay** [comment]
Thanks. so u guys have an org so that I can join  in and r u guys working on something now?

**Comment by JohJakob** [comment]
@Ananthavijay No, we don't have an organization. @tholman created Inspiring Online as a (and my) starting point for contributing to open source software. We are all working on different projects.

**Comment by Ananthavijay** [comment]
Who is tholman I haven't seen him?

**Comment by tholman** [comment]
Hey mate, thats me! Yeah, the self promotion thing is in there so we don't fill up with projects from people just trying to get their stuff out there, but rather focus on what we all find inspiring... I guess, the theory is finding your own work inspiring to yourself doesn't quite make sense?

**Comment by Ananthavijay** [comment]
sir. I didn't expect a reply from u directly

**Comment by Ananthavijay** [comment]
so can we create a org

**Comment by Ananthavijay** [comment]
?

**Comment by Ananthavijay** [comment]
?

**Comment by Ananthavijay** [comment]
I understand it @tholman

**Comment by tholman** [comment]
I don't think we need to add any more complexity to it all here. The goal is to get people confident with committing and sharing open source stuff, and keeping it simple. A few people, like JohJakob have kept up posting with some really good quality stuff, as well as helping others do the same, so I've opened it up for them as full time collaborators. It feels like we've got a handle on it all at the moment :)

**Comment by Ananthavijay** [comment]
kk

**Comment by tholman** [comment]
That said, I do want to stick with the rule. It tends to make it a little easier to manage... that said, I should do a bit of a re-jigger of the docs page, we can probably make it a little clearer, and also give people a little more of a detailed description of posting as well :)

Going to mark that down as a job for myself :)
