### ISSUE TITLE
Two posts in 1 day.

### ISSUE THREAD

**Issue by tholman** [tholman/inspiring-online#30]
Does this work, something tells me we'll need a way to order them.

**Comment by syntiux** [comment]
We could use tags as a simple way to filter for a specific type of post ( "css", "canvas", ..)

**Comment by tholman** [comment]
Was a little more concerned about making the newest post #1 ... tags are a neat idea though, something to add later on though :dancer:

**Comment by Haroenv** [comment]
Personally I use a `date` in the preamble which specifies an hour, and that's sorting them properly
