### ISSUE TITLE
[proposal] D3 Graph Theory

### ISSUE THREAD

**Issue by mrpandey** [tholman/inspiring-online#301]
[D3 Graph Theory](https://mrpandey.github.io/d3graphTheory/)
It's self promoting. But since it is not ruled out, I hope this one makes to the list.

**Comment by TJScalzo** [comment]
Sorry, but there actually is a rule against self-promotion. It’s near the [bottom of the README](https://github.com/tholman/inspiring-online#what-we-dont-like).
