### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by ChildishGiant** [tholman/inspiring-online#314]
Here's some links that 404 or are otherwise dead.

[Okay good](http://www.drewwallacegames.com/okaygood?ref=inspiring-online) 404

[Yes, No, Maybe](https://yesnomaybe.info/?ref=inspiring-online) Now redirects to another site.

[Mr. Squiggles](http://www.mrsquiggles.com/?ref=inspiring-online) completely offline

[Yeah Boiiiii](http://yeahboi.me/?ref=inspiring-online) Seems like the domain is being squatted on

[My LaCroix](http://mylacroix.com/?ref=inspiring-online) 502

I'm sure there's many more and I may make a script to check in the future but these are the ones I've ran into.

**Comment by JohJakob** [comment]
Thanks a lot, @ChildishGiant!

**Comment by ChildishGiant** [comment]
The linked PR won't fix [Yeah Boiiiii](https://github.com/tholman/inspiring-online/blob/gh-pages/_posts/2017-01-11-yeah-boiiiii.md) as that wasn't picked up by the script so I forgot to change it.
