### ISSUE TITLE
Background patterns for other categories

### ISSUE THREAD

**Issue by tholman** [tholman/inspiring-online#318]
Currently `code` has a background pattern of 0 & 1's, that sit within the triangle on the posts. I need to create some more small repetitive tiles for.
- games (space invaders tiled)
- art (perhaps some generative art)
- aesthetic (not sure)
- take my money (dollar signs)
... perhaps a couple of others

**Comment by TJScalzo** [comment]
@tholman What are your thoughts on each category having a color as well as a pattern? I feel like some color would be nice and it could make the patterns pop more.

**Comment by tholman** [comment]
Yeah, could definitely use a pop of color... tricky to keep it there without overpowering the page too much, but definitely possible

**Comment by TJScalzo** [comment]
I posted some ideas for color in #337 since this issue is focused on patterns. Colors for categories can be added independent of patterns.
