### ISSUE TITLE
Asciicker Up-to-Date?

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#323]
I noticed that in the Asciicker post the [embedded tweet](https://twitter.com/MrGumix/status/1202506831404384258) shows a recording of series "y" of the demo. However, the version(s) of the demo that are referenced throughout the post are from series "x" of the demo. Should the video and the links reference the same version of the demo in order to avoid confusion?

Also, at the end of the post it says that MrGumix is "currently working on another game." But the [tweet](https://twitter.com/MrGumix/status/989555238209249280) that is referenced is from April 26, 2018. His most recent tweets seem to be focused on Asciicker.

**Comment by tholman** [comment]
Ahh, it's no big really. Will try to keep these better up to date in the future (most of the information I got was pulled from some youtube videos people had made after discovering the game). Also keeping an eye on his account for some release info if it ever pops up.
