### ISSUE TITLE
Read More button wraps weirdly with long message

### ISSUE THREAD

**Issue by TJScalzo** [tholman/inspiring-online#327]
When the message a the Read More button/box is too long, it will wrap to a second line. While it's good that it wraps instead of continuing outside the width of the article, it leaves white space to the right of the first line that looks weird. 

Current Behavior: ![Screen Shot 2020-01-20 at 11 18 53 PM](https://user-images.githubusercontent.com/15825214/72775269-b17f2d80-3bdb-11ea-9add-df1c99f53e67.png)
Desired Behavior: ![Screen Shot 2020-01-20 at 11 20 20 PM](https://user-images.githubusercontent.com/15825214/72775273-b643e180-3bdb-11ea-912a-ac7d193b0724.png)

According to [this question](https://stackoverflow.com/questions/33244477/wrapping-text-forces-containing-element-to-max-width/33246364#33246364) and [this answer](https://stackoverflow.com/a/37413580) on StackOverflow, there isn't easy way to get rid of the extra white space since the div defaults to the maximum width when its contents wrap. As those SO posts show, the "desired behavior" can be achieved with JS that manually resizes each box to eliminate the white space. But I think the easier solution is to just make the messages short enough to stay in one line. 
For example: ![Screen Shot 2020-01-20 at 11 38 51 PM](https://user-images.githubusercontent.com/15825214/72775999-919d3900-3bde-11ea-92e0-54364fd4ae4e.png)

**Comment by TJScalzo** [comment]
Here's another example from "Now \*this\* is how you show off your new variable font."

Current Behavior: ![Screen Shot 2020-01-20 at 11 40 52 PM](https://user-images.githubusercontent.com/15825214/72776079-d628d480-3bde-11ea-9df0-6e2d69e1a3dd.png)
Desired Behavior: ![Screen Shot 2020-01-20 at 11 42 31 PM](https://user-images.githubusercontent.com/15825214/72776089-dc1eb580-3bde-11ea-8bb3-79913a6048cd.png)
Shorter Message: ![Screen Shot 2020-01-20 at 11 40 43 PM](https://user-images.githubusercontent.com/15825214/72776095-e476f080-3bde-11ea-9580-b0258a152b41.png)

**Comment by tholman** [comment]
Adding a `text-align: center` will prob be the easiest fix here

**Comment by Haroenv** [comment]
`I'm not weirded out enough yet` is slightly shorter?

**Comment by tholman** [comment]
Yeah, totally should be keeping them short to prevent the wrap... centered it now anyhow, so its covered :)
