### ISSUE TITLE
Get rid of all browser non-native code

### ISSUE THREAD

**Issue by clamiax** [tholman/inspiring-online#42]
Hi,

I love the idea of an Open Source blog so much that I'm seriously thinking to contribute. Just I wonder why you chosen to use Ruby. I guess you're a Ruby fan but we could easily use only pure HTML/JS/CSS plus a markup language to achieve our goals. Maybe some templating... if really needed.

I know it's a matter of taste but since this project is about blogging (rather than coding) I think we should be as agnostic as possible to personal technological tastes. I won't install Ruby, bundle, jekyll and so forth, just to run a simple HTML page with a bit of templating; it's a pain. Please, note that it has nothing to do with how much I like or dislike Ruby itself (it's great, btw).

Are you absolutely convinced to mantain the actual software stack or would you like to discuss about simplifying it?

Thanks for your time and sorry for my english!

Regards,
Claudio Alessi

**Comment by tholman** [comment]
Hey mate!

A few reasons here. First, and foremost, jekyll is built into github pages. Github is taking care of hosting the site, deploying new updates (when something new is pushed) as well as analytics. They're built to be one and the same... this takes a lot off my (and everyones) plate.

Secondly, this keeps the posts pristine. They live in markdown files, they are self contained, and beautiful little pieces, all alone... if we were building out a static page, for each one... we would have a lot of mess mixed in with the writing, this would make it harder for people to just get in, start writing, and feel comfortable as a whole. A html file is a lot more intimidating to someone new, compared to a markdown file.

The templating is also a huge part, in 2 years, I'll be darned if anyone would go through and update our own 100 pages of posts, to add a small bit of html. Let alone update pagination, and things like that.

In the end, if you don't like the stack, you don't really have to participate... I'm personally not the kind of person to be worried about the particular technology something is built with, but rather what we're building in the end... I guess the way I see it, is why worry about how the kite is made... its fun to fly it!

Hope that makes sense :)

**Comment by clamiax** [comment]
Hello,

I know jekyll is built into github pages, but it's also true that the project is not strictly (or shouldn't IMHO) bound to any platform. It should just be under git control, not bound to github. Since I run the repository on my own PC, not on github, I have to install jekyll (and all its evil dependencies):

```
$ jekyl
/bin/mksh: jekyl: not found
```

Also I already have a web server running on my machine, my favourite web server, not sure what may be the point in favour of jekyl but I'm pretty sure it somewhat violates my freedom to use what is the best tool for me. In general, forcing users to use "this" instead of "that" is not good IMHO.

I don't want to remove the markdown engine, even if I think a markdown is not clearer than a clean HTML markup in most cases; though this may be a matter of taste. But using a markdown engine don't really need the actual stack you use, anyway. Navigation and other dynamic stuff may be generated in many ways, none of which requires to install Ruby, jekyll, bundle, and who know what more (dependencies). Also a makefile would be better than the actual situations.

I think people should focus on writing articles not playing around with installing lots of software just to write some line of text. This is also in respect of users freedom to choose what tools they think are the best. I agree that it's fun to fly, but we may have a different meaning of what "fly" means.

This is just to clarify my point of view. Though, since you don't really care about new contribution ("if you don't like the stack just don't partecipate") I indeed decided to not partecipate.
