### ISSUE TITLE
[proposal] - Why Skeuomorphism Is Like a Classic Car

### ISSUE THREAD

**Issue by vaidaslamanauskas** [tholman/inspiring-online#53]
https://vimeo.com/116295698

Should I submit a pull request for full post?

**Comment by JohJakob** [comment]
@vaidaslamanauskas Yep!

**Comment by tholman** [comment]
Definitely :)

**Comment by vaidaslamanauskas** [comment]
Will do.

**Comment by tholman** [comment]
I don't think we have anything built in yet to handle vimeo urls... but I'd look at how youtube ones are added, and copy that :)

**Comment by tholman** [comment]
Although if you don't want to do that (I can later! there are plenty of other proposed things too... can make a post from any of them!)

**Comment by vaidaslamanauskas** [comment]
Yes. I'll do it. Vimeo embeds will be useful later anyway.
