### ISSUE TITLE
[proposal] - Color Claim

### ISSUE THREAD

**Issue by vaidaslamanauskas** [tholman/inspiring-online#57]
http://colorclaim.tumblr.com/

**Comment by TJScalzo** [comment]
I don't think I understand what this tumblr page is about. It seems to be a bunch of images? I don't know if it'd work on the site.

**Comment by vaidaslamanauskas** [comment]
It is one of the best color combination sites I've seen on the web. It is an oldie.

**Comment by TJScalzo** [comment]
Got it

**Comment by tholman** [comment]
Just talked to the owner of the site too... he's doing a redesign now. So lets hold off until its done! Will be extra nice :dancer:

**Comment by TJScalzo** [comment]
Got it, sounds good.

**Comment by tholman** [comment]
Added.
