### ISSUE TITLE
[proposal] - Fanfare

### ISSUE THREAD

**Issue by vaidaslamanauskas** [tholman/inspiring-online#84]
http://www.audepicault.com/fanfare/fanfare.htm

**Comment by JohJakob** [comment]
@vaidaslamanauskas This is cool! …but it doesn't work in Safari and Firefox.

**Comment by TJScalzo** [comment]
It seems to work fine for me. I'm using Safari so perhaps it's been fixed since you looked at it @JohJakob?

**Comment by JohJakob** [comment]
@TJScalzo It still doesn't work for me.

**Comment by Haroenv** [comment]
Yeah, doesn't work for me on Safari or FF either, don't really get why because there are no errors.

**Comment by TJScalzo** [comment]
@JohJakob @Haroenv that's odd... It could be because I have a really old version of Safari. I'm not really sure why it works for me. Oh well, we don't want to post something that only works for certain people.

**Comment by JohJakob** [comment]
@TJScalzo @Haroenv Should I close this issue?

**Comment by TJScalzo** [comment]
@JohJakob you probably should since it doesn't work for most people.
