### ISSUE TITLE
[proposal] - australia.css

### ISSUE THREAD

**Issue by JohJakob** [tholman/inspiring-online#85]
https://bullg.it/australia.css
https://github.com/bullgit/australia.css
@tholman :wink:

**Comment by JohJakob** [comment]
@tholman
> Please don't post your own things. I know self promoting is fun, but it's kind of against the spirit of what we're trying to do.

What do you think? @Haroenv made australia.css, but he is now a contributor…

**Comment by tholman** [comment]
Haha, you submitted it, not him... definitely fine! :dancer:

**Comment by JohJakob** [comment]
:+1:

By the way, thank you!
> You can now push to this repository.

**Comment by tholman** [comment]
:)
