### ISSUE TITLE
[suggestion] - New icon/logo

### ISSUE THREAD

**Issue by JohJakob** [tholman/inspiring-online#88]
Hey guys,
I've made a new icon/logo for Inspiring Online. What do you think? Should we use it?

![Inspiring Online Icon](https://cloud.githubusercontent.com/assets/9888537/12714557/c8589b54-c8d5-11e5-8883-e450ad15a478.png)

**Comment by vaidaslamanauskas** [comment]
I think it is too sensible. It's needs something weird, maybe. Slightly mad, stupid :)

**Comment by tholman** [comment]
I do like it!

Not sure where it would go though. That said, I also really like the quirky
i.o face thing in the current emoticon.

Your call! :D

On Tue, Feb 2, 2016 at 10:13 AM, Vaidas L. <notifications@github.com> wrote:

> I think it is too sensible. It's needs something weird, maybe. Slightly
> mad, stupid :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tholman/inspiring-online/issues/88#issuecomment-178626258>
> .
>



-- 
Tim Holman
tholman.com

**Comment by JohJakob** [comment]
I'm going to make it a bit crazier…

**Comment by JohJakob** [comment]
![Inspiring Online Icon](https://cloud.githubusercontent.com/assets/9888537/12855451/d3aa2492-cc3f-11e5-84d5-72d7565dab0b.png)

#WideWeirdWeb

**Comment by tholman** [comment]
True love.

**Comment by JohJakob** [comment]
:heart:

**Comment by krikmo** [comment]
Beautiful.

**Comment by JohJakob** [comment]
@krikmo Thanks!
